[build]
  command = "npm run build"
  publish = "dist"
  image = "ubuntu-noble-22.04"

[build.environment]
  NODE_VERSION = "22.15.0"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_YARN = "false"

# Configuração para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 